plugins {
	id 'org.springframework.restdocs.conventions'
	id "java-library"
	id "maven-publish"
}

description = "Spring REST Docs RestTestClient"

dependencies {
	api(project(":spring-restdocs-core"))
	api("org.springframework:spring-test")
	api("org.springframework:spring-web")

	implementation("jakarta.servlet:jakarta.servlet-api")

	compileOnly("org.hamcrest:hamcrest-core")
	compileOnly("com.google.code.findbugs:jsr305")

	testCompileOnly("org.hamcrest:hamcrest-core")

	testImplementation(testFixtures(project(":spring-restdocs-core")))
	testImplementation("org.springframework:spring-webmvc")

	testRuntimeOnly("org.springframework:spring-context")
}

tasks.named("compileTestJava") {
	options.nullability.checking = "tests"
}
