[[documenting-your-api.form-parameters]]
= Form Parameters

You can document a request's form parameters by using `formParameters`.
The following examples show how to do so:

[tabs]
====
MockMvc::
+
include-code::mockmvc/FormParameters[]
<1> Perform a `POST` request with a single form parameter, `username`.
<2> Configure Spring REST Docs to produce a snippet describing the request's form parameters.
Uses the static `formParameters` method on `org.springframework.restdocs.request.RequestDocumentation`.
<3> Document the `username` parameter.
Uses the static `parameterWithName` method on `org.springframework.restdocs.request.RequestDocumentation`.

WebTestClient::
+
include-code::webtestclient/FormParameters[]
<1> Perform a `POST` request with a single form parameter, `username`.
<2> Configure Spring REST Docs to produce a snippet describing the request's form parameters.
Uses the static `formParameters` method on `org.springframework.restdocs.request.RequestDocumentation`.
<3> Document the `username` parameter.
Uses the static `parameterWithName` method on `org.springframework.restdocs.request.RequestDocumentation`.
====

In all cases, the result is a snippet named `form-parameters.adoc` that contains a table describing the form parameters that are supported by the resource.

When documenting form parameters, the test fails if an undocumented form parameter is used in the request body.
Similarly, the test also fails if a documented form parameter is not found in the request body and the form parameter has not been marked as optional.

If you do not want to document a form parameter, you can mark it as ignored.
This prevents it from appearing in the generated snippet while avoiding the failure described above.

You can also document form parameters in a relaxed mode where any undocumented parameters do not cause a test failure.
To do so, use the `relaxedFormParameters` method on `org.springframework.restdocs.request.RequestDocumentation`.
This can be useful when documenting a particular scenario where you only want to focus on a subset of the form parameters.
