[[documenting-your-api.http-headers]]
= HTTP Headers

You can document the headers in a request or response by using `requestHeaders` and `responseHeaders`, respectively.
The following examples show how to do so:

[tabs]
====
MockMvc::
+
include-code::mockmvc/HttpHeaders[]
<1> Perform a `GET` request with an `Authorization` header that uses basic authentication.
<2> Configure Spring REST Docs to produce a snippet describing the request's headers.
Uses the static `requestHeaders` method on `org.springframework.restdocs.headers.HeaderDocumentation`.
<3> Document the `Authorization` header.
Uses the static `headerWithName` method on `org.springframework.restdocs.headers.HeaderDocumentation`.
<4> Produce a snippet describing the response's headers.
Uses the static `responseHeaders` method on `org.springframework.restdocs.headers.HeaderDocumentation`.

WebTestClient::
+
include-code::webtestclient/HttpHeaders[]
<1> Perform a `GET` request with an `Authorization` header that uses basic authentication.
<2> Configure Spring REST Docs to produce a snippet describing the request's headers.
Uses the static `requestHeaders` method on `org.springframework.restdocs.headers.HeaderDocumentation`.
<3> Document the `Authorization` header.
Uses the static `headerWithName` method on `org.springframework.restdocs.headers.HeaderDocumentation`.
<4> Produce a snippet describing the response's headers.
Uses the static `responseHeaders` method on `org.springframework.restdocs.headers.HeaderDocumentation`.
====

The result is a snippet named `request-headers.adoc` and a snippet named `response-headers.adoc`.
Each contains a table describing the headers.

When documenting HTTP Headers, the test fails if a documented header is not found in the request or response.
