[[configuration]]
== Configuration



[[configuration-uris]]
=== Documented URIs

The default configuration for URIs documented by Spring REST Docs is:

|===
|Setting |Default

|Scheme
|`http`

|Host
|`localhost`

|Port
|`8080`
|===

This configuration is applied by `RestDocumentationMockMvcConfigurer`. You can use its API
to change one or more of the defaults to suit your needs:

[source,java,indent=0]
----
include::{examples-dir}/com/example/CustomUriConfiguration.java[tags=custom-uri-configuration]
----

TIP: To configure a request's context path, use the `contextPath` method on
`MockHttpServletRequestBuilder`.



[[configuration-snippet-encoding]]
=== Snippet encoding

The default encoding used by Asciidoctor is `UTF-8`. Spring REST Docs adopts the same
default for the snippets that it generates. If you require an encoding other than `UTF-8`,
use `RestDocumentationMockMvcConfigurer` to configure it:

[source,java,indent=0]
----
include::{examples-dir}/com/example/CustomEncoding.java[tags=custom-encoding]
----

TIP: When Spring REST Docs converts a request or response's content to a String, the
`charset` specified in the `Content-Type` header will be used if it is available. In its
absence, the JVM's default `Charset` will be used. The JVM's default `Charset` can be
configured using the `file.encoding` system property.



[[configuration-default-snippets]]
=== Default snippets

Three snippets are produced by default:

- `curl-request`
- `http-request`
- `http-response`

This default configuration is applied by `RestDocumentationMockMvcConfigurer`. You can use
its API to change the configuration. For example, to only produce the `curl-request`
snippet by default:

[source,java,indent=0]
----
include::{examples-dir}/com/example/CustomDefaultSnippetsConfiguration.java[tags=custom-default-snippets]
----