[[documenting-your-api]]
== Documenting your API

This section provides more details about using Spring REST Docs to document your API.



[[documenting-your-api-hypermedia]]
=== Hypermedia

Spring REST Docs provides support for documenting the links in a
https://en.wikipedia.org/wiki/HATEOAS[Hypermedia-based] API:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Hypermedia.java[tag=links]
----
<1> Use `withLinks` is to describe the expected links.
<2> Expect a link whose rel is `alpha`. Uses the static `linkWithRel` method on
`org.springframework.restdocs.hypermedia.HypermediaDocumentation`.
<3> Expect a link whose rel is `bravo`.

The result is a snippet named `links.adoc` that contains a table describing the resource's
links.

When documenting links, the test will fail if an undocumented link is found in the
response. Similarly, the test will also fail if a documented link is not found in the
response and the link has not been marked as optional.



[[documenting-your-api-hypermedia-link-formats]]
==== Hypermedia link formats

Two link formats are understood by default:

 * Atom – links are expected to be in an array named `links`. Used by default when the
   content type of the response is compatible with `application/json`.
 * HAL – links are expected to be in a map named `_links`. Used by default when the
   content type of the response is compatible with `application/hal+json`.

If you are using Atom or HAL-format links but with a different content type you can
provide one of the built-in `LinkExtractor` implementations to `withLinks`. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Hypermedia.java[tag=explicit-extractor]
----
<1> Indicate that the links are in HAL format. Uses the static `halLinks` method on
`org.springframework.restdocs.hypermedia.LinkExtractors`.

If your API represents its links in a format other than Atom or HAL you can provide your
own implementation of the `LinkExtractor` interface to extract the links from the
response.

[[documenting-your-api-request-response-payloads]]
=== Request and response payloads

In addition to the Hypermedia-specific support <<documenting-your-api-hypermedia,described
above>>, support for general documentation of request and response payloads is also
provided:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=response]
----
<1> Use `withResponseFields` to describe the expected fields in the response payload.
To document a request `withRequestFields` can be used.
<2> Expect a field with the path `contact`. Uses the static `fieldWithPath` method on
`org.springframework.restdocs.payload.PayloadDocumentation`.
<3> Expect a field with the path `contact.email`.

The result is a snippet that contains a table describing the fields. For requests this
snippet is named `request-fields.adoc`. For responses this snippet is named
`response-fields.adoc`.

When documenting fields, the test will fail if an undocumented field is found in the
payload. Similarly, the test will also fail if a documented field is not found in the
payload and the field has not been marked as optional. For payloads with a hierarchical
structure, documenting a field is sufficient for all of its descendants to also be
treated as having been documented.

[[documenting-your-api-request-response-payloads-field-paths]]
==== Field paths

When documenting request and response payloads, fields are identified using a path. Paths
use `.` to descend into a child object and `[]` to identify an array. For example, with
this JSON payload:

[source,json,indent=0]
----
	{
		"a":{
			"b":[
				{
					"c":"one"
				},
				{
					"c":"two"
				},
				{
					"d":"three"
				}
			]
		}
	}
----

The following paths are all present:

[cols="1,3"]
|===
|Path | Value

|`a`
|An object containing `b`

|`a.b`
|An array containing three objects

|`a.b[]`
|An array containing three objects

|`a.b[].c`
|An array containing the strings `one` and `two`

|`a.b[].d`
|The string `three`
|===



[[documenting-your-api-request-response-payloads-field-types]]
==== Field types

When a field is documented, Spring REST Docs will attempt to determine its type by
examining the payload. Seven different types are supported:

[cols="1,3"]
|===
| Type | Description

| array
| The value of each occurrence of the field is an array

| boolean
| The value of each occurrence of the field is a boolean (`true` or `false`)

| object
| The value of each occurrence of the field is an object

| number
| The value of each occurrence of the field is a number

| null
| The value of each occurrence of the field is `null`

| string
| The value of each occurrence of the field is a string

| varies
| The field occurs multiple times in the payload with a variety of different types
|===

The type can also be set explicitly using the `type(FieldType)` method on
`FieldDescriptor`:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=explicit-type]
----
<1> Set the field's type to `string`.



[[documenting-your-api-query-parameters]]
=== Query parameters

A request's query parameters can be documented using `withQueryParameters`

[source,java,indent=0]
----
include::{examples-dir}/com/example/QueryParameters.java[tags=query-parameters]
----
<1> Use `withQueryParameters` to describe the query parameters.
<2> Document a parameter named `page`. Uses the static `parameterWithName` method on
`org.springframework.restdocs.request.RequestDocumentation`.
<3> Document a parameter named `per_page`.

The result is a snippet named `query-parameters.adoc` that contains a table describing
the query parameters that are supported by the resource.

When documenting query parameters, the test will fail if an undocumented query parameter
is used in the request. Similarly, the test will also fail if a documented query parameter
is not found in the request.



[[documenting-your-api-path-parameters]]
=== Path parameters

A request's path parameters can be documented using `withPathParameters`

[source,java,indent=0]
----
include::{examples-dir}/com/example/PathParameters.java[tags=path-parameters]
----
<1> Build the request. Uses the static `get` method on `RestDocumentationRequestBuilders`.
<2> Use `withPathParameters` to describe the path parameters.
<3> Document a parameter named `longitude`. Uses the static `parameterWithName` method on
`org.springframework.restdocs.request.RequestDocumentation`.
<4> Document a parameter named `latitude`.

The result is a snippet named `path-parameters.adoc` that contains a table describing
the path parameters that are supported by the resource.

When documenting path parameters, the test will fail if an undocumented path parameter
is used in the request. Similarly, the test will also fail if a documented path parameter
is not found in the request.

TIP: To make the path parameters available for documentation, the request must be
built using one of the methods on `RestDocumentationRequestBuilders` rather than
`MockMvcRequestBuilders`.

[[documenting-your-api-default-snippets]]
=== Default snippets

A number of snippets are produced automatically when you document a call to
`MockMvc.perform`:

[cols="1,3"]
|===
|Snippet | Description

| `curl-request.adoc`
| Contains the http://curl.haxx.se[`curl`] command that is equivalent to the `MockMvc`
call that is being documented

| `http-request.adoc`
| Contains the HTTP request that is equivalent to the `MockMvc` call that is being
documented

| `http-response.adoc`
| Contains the HTTP response that was returned
|===



[[documentating-your-api-parameterized-output-directories]]
=== Using parameterized output directories

The output directory used by `document` can be parameterized. The following parameters
are supported:

[cols="1,3"]
|===
| Parameter | Description

| {methodName}
| The name of the test method, formatted using camelCase

| {method-name}
| The name of the test method, formatted using kebab-case

| {method_name}
| The name of the test method, formatted using snake_case

| {step}
| The count of calls to MockMvc.perform in the current test
|===

For example, `document("{method-name}")` in a test method named `creatingANote` will write
snippets into a directory named `creating-a-note`.

The `{step}` parameter is particularly useful in combination with Spring MVC Test's
`alwaysDo` functionality. It allows documentation to be configured once in a setup method:

[source,java,indent=0]
----
include::{examples-dir}/com/example/AlwaysDo.java[tags=always-do]
----

With this configuration in place, every call to `MockMvc.perform` will produce
the <<documenting-your-api-default-snippets,default snippets>> without any further
configuration. Take a look at the `GettingStartedDocumentation` classes in each of the
sample applications to see this functionality in action.



[[documenting-your-api-customizing]]
=== Customizing the output



[[documenting-your-api-customizing-snippets]]
==== Customizing the generated snippets
Spring REST Docs uses https://mustache.github.io[Mustache] templates to produce the
generated snippets.
{source}spring-restdocs/src/main/resources/org/springframework/restdocs/templates[Default
templates] are provided for each of the snippets that Spring REST Docs can produce. To
customize a snippet's content, you can provide your own template.

Templates are loaded from the classpath in the `org.springframework.restdocs.templates`
package and each template is named after the snippet that it will produce. For example, to
override the template for the `curl-request.adoc` snippet, create a template named
`curl-request.snippet` in `src/test/resources/org/springframework/restdocs/templates`.



[[documenting-your-api-customizing-including-extra-information]]
==== Including extra information

There are two ways to provide extra information for inclusion in a generated snippet:

. Use the `attributes` method on a field, link or parameter descriptor to add one or more
  attributes to an individual descriptor.
. Pass in some attributes when calling `withCurlRequest`, `withHttpRequest`,
  `withHttpResponse`, etc on `RestDocumentationResultHandler`. Such attributes will be
  associated with the snippet as a whole.

Any additional attributes are made available during the template rendering process.
Coupled with a custom snippet template, this makes it possible to include extra
information in a generated snippet.

A concrete example of the above is the addition of a constraints column and a title when
documenting request fields. The first step is to provide a `constraints` attribute for
each field that you are documenting and to provide a `title` attribute:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=constraints]
----
<1> Configure the `title` attribute for the request fields snippet
<2> Set the `constraints` attribute for the `name` field
<3> Set the `constraints` attribute for the `email` field

The second step is to provide a custom template named `request-fields.snippet` that
includes the information about the fields' constraints in the generated snippet's table
and adds a title:

[source,indent=0]
----
	.{{title}} <1>
	|===
	|Path|Type|Description|Constraints <2>

	{{#fields}}
	|{{path}}
	|{{type}}
	|{{description}}
	|{{constraints}} <3>

	{{/fields}}
	|===
----
<1> Add a title to the table
<2> Add a new column named "Constraints"
<3> Include the descriptors' `constraints` attribute in each row of the table


