[[documenting-your-api]]
== Documenting your API

This section provides more details about using Spring REST Docs to document your API.



[[documenting-your-api-hypermedia]]
=== Hypermedia

Spring REST Docs provides support for documenting the links in a
https://en.wikipedia.org/wiki/HATEOAS[Hypermedia-based] API:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Hypermedia.java[tag=links]
----
<1> Produce a snippet describing the response's links. Uses the static `links` method on
`org.springframework.restdocs.hypermedia.HypermediaDocumentation`.
<2> Expect a link whose rel is `alpha`. Uses the static `linkWithRel` method on
`org.springframework.restdocs.hypermedia.HypermediaDocumentation`.
<3> Expect a link whose rel is `bravo`.

The result is a snippet named `links.adoc` that contains a table describing the resource's
links.

When documenting links, the test will fail if an undocumented link is found in the
response. Similarly, the test will also fail if a documented link is not found in the
response and the link has not been marked as optional.



[[documenting-your-api-hypermedia-link-formats]]
==== Hypermedia link formats

Two link formats are understood by default:

 * Atom – links are expected to be in an array named `links`. Used by default when the
   content type of the response is compatible with `application/json`.
 * HAL – links are expected to be in a map named `_links`. Used by default when the
   content type of the response is compatible with `application/hal+json`.

If you are using Atom or HAL-format links but with a different content type you can
provide one of the built-in `LinkExtractor` implementations to `links`. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Hypermedia.java[tag=explicit-extractor]
----
<1> Indicate that the links are in HAL format. Uses the static `halLinks` method on
`org.springframework.restdocs.hypermedia.HypermediaDocumentation`.

If your API represents its links in a format other than Atom or HAL you can provide your
own implementation of the `LinkExtractor` interface to extract the links from the
response.

[[documenting-your-api-request-response-payloads]]
=== Request and response payloads

In addition to the hypermedia-specific support <<documenting-your-api-hypermedia,described
above>>, support for general documentation of request and response payloads is also
provided. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=response]
----
<1> Use `responseFields` to describe the expected fields in the response payload.
To document a request `requestFields` can be used. Both are static methods on
`org.springframework.restdocs.payload.PayloadDocumentation`.
<2> Expect a field with the path `contact`. Uses the static `fieldWithPath` method on
`org.springframework.restdocs.payload.PayloadDocumentation`.
<3> Expect a field with the path `contact.email`.

The result is a snippet that contains a table describing the fields. For requests this
snippet is named `request-fields.adoc`. For responses this snippet is named
`response-fields.adoc`.

When documenting fields, the test will fail if an undocumented field is found in the
payload. Similarly, the test will also fail if a documented field is not found in the
payload and the field has not been marked as optional. For payloads with a hierarchical
structure, documenting a field is sufficient for all of its descendants to also be
treated as having been documented.

TIP: By default, Spring REST Docs will assume that the payload you are documenting is
JSON. If you want to document an XML payload the content type of the request or response
must be compatible with `application/xml`.

[[documenting-your-api-request-response-payloads-json]]
==== JSON payloads

[[documenting-your-api-request-response-payloads-json-field-paths]]
===== JSON field paths

JSON field paths use `.` to descend into a child object and `[]` to identify an array. For
example, with this JSON payload:

[source,json,indent=0]
----
	{
		"a":{
			"b":[
				{
					"c":"one"
				},
				{
					"c":"two"
				},
				{
					"d":"three"
				}
			]
		}
	}
----

The following paths are all present:

[cols="1,3"]
|===
|Path | Value

|`a`
|An object containing `b`

|`a.b`
|An array containing three objects

|`a.b[]`
|An array containing three objects

|`a.b[].c`
|An array containing the strings `one` and `two`

|`a.b[].d`
|The string `three`
|===



[[documenting-your-api-request-response-payloads-json-field-types]]
===== JSON field types

When a field is documented, Spring REST Docs will attempt to determine its type by
examining the payload. Seven different types are supported:

[cols="1,3"]
|===
| Type | Description

| array
| The value of each occurrence of the field is an array

| boolean
| The value of each occurrence of the field is a boolean (`true` or `false`)

| object
| The value of each occurrence of the field is an object

| number
| The value of each occurrence of the field is a number

| null
| The value of each occurrence of the field is `null`

| string
| The value of each occurrence of the field is a string

| varies
| The field occurs multiple times in the payload with a variety of different types
|===

The type can also be set explicitly using the `type(Object)` method on
`FieldDescriptor`. Typically, one of the values enumerated by `JsonFieldType` will be
used:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=explicit-type]
----
<1> Set the field's type to `string`.


[[documenting-your-api-request-response-payloads-xml]]
==== XML payloads

[[documenting-your-api-request-response-payloads-xml-field-paths]]
===== XML field paths

XML field paths are described using XPath. `/` is used to descend into a child node.



[[documenting-your-api-request-response-payloads-xml-field-types]]
===== XML field types

When documenting an XML payload, you must provide a type for the field using the
`type(Object)` method on `FieldDescriptor`. The result of the supplied type's `toString`
method will be included in the documentation.



[[documenting-your-api-request-parameters]]
=== Request parameters

A request's parameters can be documented using `requestParameters`. Request parameters
can be included in a `GET` request's query string. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/RequestParameters.java[tags=request-parameters-query-string]
----
<1> Perform a `GET` request with two parameters, `page` and `per_page` in the query
	string.
<2> Produce a snippet describing the request's parameters. Uses the static
`requestParameters` method on `org.springframework.restdocs.request.RequestDocumentation`.
<3> Document the `page` parameter. Uses the static `parameterWithName` method on
`org.springframework.restdocs.request.RequestDocumentation`.
<4> Document the `per_page` parameter.

Request parameters can also be included as form data in the body of a POST request:

[source,java,indent=0]
----
include::{examples-dir}/com/example/RequestParameters.java[tags=request-parameters-form-data]
----
<1> Perform a `POST` request with a single parameter, `username`.

In both cases, the result is a snippet named `request-parameters.adoc` that contains a
table describing the parameters that are supported by the resource.

When documenting request parameters, the test will fail if an undocumented request
parameter is used in the request. Similarly, the test will also fail if a documented
request parameter is not found in the request.



[[documenting-your-api-path-parameters]]
=== Path parameters

A request's path parameters can be documented using `pathParameters`. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/PathParameters.java[tags=path-parameters]
----
<1> Perform a `GET` request with two path parameters, `latitude` and `longitude`.
<2> Produce a snippet describing the request's path parameters. Uses the static
`pathParameters` method on `org.springframework.restdocs.request.RequestDocumentation`.
<3> Document the parameter named `latitude`. Uses the static `parameterWithName` method on
`org.springframework.restdocs.request.RequestDocumentation`.
<4> Document the parameter named `longitude`.

The result is a snippet named `path-parameters.adoc` that contains a table describing
the path parameters that are supported by the resource.

When documenting path parameters, the test will fail if an undocumented path parameter
is used in the request. Similarly, the test will also fail if a documented path parameter
is not found in the request.

TIP: To make the path parameters available for documentation, the request must be
built using one of the methods on `RestDocumentationRequestBuilders` rather than
`MockMvcRequestBuilders`.



[[documenting-your-api-constraints]]
=== Documenting constraints

Spring REST Docs provides a number of classes that can help you to document constraints.
An instance of `ConstraintDescriptions` can be used to access descriptions of a class's
constraints. For example:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Constraints.java[tags=constraints]
----
<1> Create an instance of `ConstraintDescriptions` for the `UserInput` class
<2> Get the descriptions of the name property's constraints. This list will contain two
	descriptions; one for the `NotNull` constraint and one for the `Size` constraint.

The `ApiDocumentation` class in the Spring HATEOAS sample shows this functionality in
action.



[[documenting-your-api-constraints-finding]]
==== Finding constraints

By default, constraints are found using a Bean Validation `Validator`. Currently, only
property constraints are supported. You can customize the `Validator` that's used by
creating `ConstraintDescriptions` with a custom `ValidatorConstraintResolver` instance.
To take complete control of constraint resolution, your own implementation of
`ConstraintResolver` can be used.



[[documenting-your-api-constraints-describing]]
==== Describing constraints

Default descriptions are provided for all of the Bean Validation 1.1's constraints:

* AssertFalse
* AssertTrue
* DecimalMax
* DecimalMin
* Digits
* Future
* Max
* Min
* NotNull
* Null
* Past
* Pattern
* Size

To override the default descriptions, or to provide a new description, create a resource
bundle with the base name
`org.springframework.restdocs.constraints.ConstraintDescriptions`.  The Spring
HATEOAS-based sample contains
{samples}/rest-notes-spring-hateoas/src/test/resources/org/springframework/restdocs/constraints/ConstraintDescriptions.properties[an
example of such a resource bundle].

Each key in the resource bundle is the fully-qualified name of a constraint plus
`.description`. For example, the key for the standard `@NotNull` constraint is
`javax.validation.constraints.NotNull.description`.

Property placeholder's referring to a constraint's attributes can be used in its
description. For example, the default description of the `@Min` constraint,
`Must be at least ${value}`, refers to the constraint's `value` attribute.

To take more control of constraint description resolution, create `ConstraintDescriptions`
with a custom `ResourceBundleConstraintDescriptionResolver`. To take complete control,
create `ConstraintDescriptions` with a custom `ConstraintDescriptionResolver`
implementation.



==== Using constraint descriptions in generated snippets

Once you have a constraint's descriptions, you're free to use them however you like in
the generated snippets. For example, you may want to include the constraint descriptions
as part of a field's description. Alternatively, you could include the constraints as
<<documenting-your-api-customizing-including-extra-information, extra information>> in
the request fields snippet. The
{samples}/rest-notes-spring-hateoas/src/test/java/com/example/notes/ApiDocumentation.java[`ApiDocumentation`]
class in the Spring HATEOAS-based sample illustrates the latter approach.



[[documenting-your-api-default-snippets]]
=== Default snippets

A number of snippets are produced automatically when you document a call to
`MockMvc.perform`:

[cols="1,3"]
|===
|Snippet | Description

| `curl-request.adoc`
| Contains the http://curl.haxx.se[`curl`] command that is equivalent to the `MockMvc`
call that is being documented

| `http-request.adoc`
| Contains the HTTP request that is equivalent to the `MockMvc` call that is being
documented

| `http-response.adoc`
| Contains the HTTP response that was returned
|===

You can configure which snippets are produced by default. Please refer to the
<<configuration, configuration section>> for more information.



[[documentating-your-api-parameterized-output-directories]]
=== Using parameterized output directories

The output directory used by `document` can be parameterized. The following parameters
are supported:

[cols="1,3"]
|===
| Parameter | Description

| {methodName}
| The name of the test method, formatted using camelCase

| {method-name}
| The name of the test method, formatted using kebab-case

| {method_name}
| The name of the test method, formatted using snake_case

| {step}
| The count of calls to MockMvc.perform in the current test
|===

For example, `document("{method-name}")` in a test method named `creatingANote` will write
snippets into a directory named `creating-a-note`.

A parameterized output directory is particularly useful in combination with Spring MVC
Test's `alwaysDo` functionality. It allows documentation to be configured once in a setup method:

[source,java,indent=0]
----
include::{examples-dir}/com/example/AlwaysDo.java[tags=always-do]
----

With this configuration in place, every call to `MockMvc.perform` will produce
the <<documenting-your-api-default-snippets,default snippets>> without any further
configuration. Take a look at the `GettingStartedDocumentation` classes in each of the
sample applications to see this functionality in action.



[[documenting-your-api-customizing]]
=== Customizing the output



[[documenting-your-api-customizing-snippets]]
==== Customizing the generated snippets
Spring REST Docs uses https://mustache.github.io[Mustache] templates to produce the
generated snippets.
{source}spring-restdocs/src/main/resources/org/springframework/restdocs/templates[Default
templates] are provided for each of the snippets that Spring REST Docs can produce. To
customize a snippet's content, you can provide your own template.

Templates are loaded from the classpath in the `org.springframework.restdocs.templates`
package and each template is named after the snippet that it will produce. For example, to
override the template for the `curl-request.adoc` snippet, create a template named
`curl-request.snippet` in `src/test/resources/org/springframework/restdocs/templates`.



[[documenting-your-api-customizing-including-extra-information]]
==== Including extra information

There are two ways to provide extra information for inclusion in a generated snippet:

. Use the `attributes` method on a field, link or parameter descriptor to add one or more
  attributes to an individual descriptor.
. Pass in some attributes when calling `curlRequest`, `httpRequest`, `httpResponse`, etc.
  Such attributes will be associated with the snippet as a whole.

Any additional attributes are made available during the template rendering process.
Coupled with a custom snippet template, this makes it possible to include extra
information in a generated snippet.

A concrete example of the above is the addition of a constraints column and a title when
documenting request fields. The first step is to provide a `constraints` attribute for
each field that you are documenting and to provide a `title` attribute:

[source,java,indent=0]
----
include::{examples-dir}/com/example/Payload.java[tags=constraints]
----
<1> Configure the `title` attribute for the request fields snippet
<2> Set the `constraints` attribute for the `name` field
<3> Set the `constraints` attribute for the `email` field

The second step is to provide a custom template named `request-fields.snippet` that
includes the information about the fields' constraints in the generated snippet's table
and adds a title:

[source,indent=0]
----
	.{{title}} <1>
	|===
	|Path|Type|Description|Constraints <2>

	{{#fields}}
	|{{path}}
	|{{type}}
	|{{description}}
	|{{constraints}} <3>

	{{/fields}}
	|===
----
<1> Add a title to the table
<2> Add a new column named "Constraints"
<3> Include the descriptors' `constraints` attribute in each row of the table


