= RESTful Notes User Guide
Andy Wilkinson;
:doctype: book
:toc:
:toclevels: 4
:source-highlighter: highlightjs

[introduction]
= Introduction

RESTful Notes is a RESTful web service for creating and storing notes. It uses hypermedia
to describe the relationships between resources and to allow navigation between them.

[getting-started]
= Getting started



[getting-started-running-the-service]
== Running the service
RESTful Notes is written using http://projects.spring.io/spring-boot[Spring Boot] which
makes it easy to get it up and running so that you can start exploring the REST API.

At the moment, binaries for RESTful Notes are not published anywhere. However, building
and running it from source is straightforward. The first step is to clone the Git
repository:

[source,bash]
----
$ git clone https://github.com/wilkinsona/spring-restdocs
----

Once the clone is complete, you're ready to get the service up and running:

[source,bash]
----
$ cd rest-notes
$ ./gradlew build
$ java -jar build/libs/*.jar
----

You can check that the service is up and running by executing a simple request using
cURL:

include::{generated}/index/request.asciidoc[]

This request should yield the following response:

include::{generated}/index/response.asciidoc[]

Note the `_links` in the JSON response. They are key to navigating the API.



[getting-started-creating-a-note]
== Creating a note
Now that you've started the service and verified that it works, the next step is to use
it to create a new note. As you saw above, the URI for working with notes is included as
a link when you perform a `GET` request against the root of the service:

include::{generated}/index/response.asciidoc[]

To create a note you need to execute a `POST` request to this URI, including a JSON
payload containing the title and body of the note:

include::{generated}/create-note/request.asciidoc[]

The response from this request should have a status code of `201 Created` and contain a
`Location` header whose value is the URI of the newly created note:

include::{generated}/create-note/response.asciidoc[]

To work with the newly created note you use the URI in the `Location` header. For example
you can access the note's details by performing a `GET` request:

include::{generated}/get-note/request.asciidoc[]

This request will produce a response with the note's details in its body:

include::{generated}/get-note/response.asciidoc[]

Note the `note-tags` link which we'll make use of later.



[getting-started-creating-a-tag]
== Creating a tag
To make a note easier to find, it can be associated with any number of tags. To be able
to tag a note, you must first create the tag.

Referring back to the response for the service's index, the URI for working with tags is
include as a link:

include::{generated}/index/response.asciidoc[]

To create a tag you need to execute a `POST` request to this URI, including a JSON
payload containing the name of the tag:

include::{generated}/create-tag/request.asciidoc[]

The response from this request should have a status code of `201 Created` and contain a
`Location` header whose value is the URI of the newly created tag:

include::{generated}/create-tag/response.asciidoc[]

To work with the newly created tag you use the URI in the `Location` header. For example
you can access the tag's details by performing a `GET` request:

include::{generated}/get-tag/request.asciidoc[]

This request will produce a response with the tag's details in its body:

include::{generated}/get-tag/response.asciidoc[]



[getting-started-tagging-a-note]
== Tagging a note
A tag isn't particularly useful until it's been associated with one or more notes. There
are two ways to tag a note: when the note is first created or by updating an existing
note. We'll look at both of these in turn.



[getting-started-tagging-a-note-creating]
=== Creating a tagged note
The process is largely the same as we saw before, but this time, in addition to providing
a title and body for the note, we'll also provide the tag that we want to be associated
with it.

Once again we execute a `POST` request, but this time, in an array named tags, we include
the URI of the tag we just created:

include::{generated}/create-tagged-note/request.asciidoc[]

Once again, the response's `Location` header tells use the URI of the newly created note:

include::{generated}/create-tagged-note/response.asciidoc[]

As before, a `GET` request executed against this URI will retrieve the note's details:

include::{generated}/get-tagged-note/request-response.asciidoc[]

To see the note's tags, execute a `GET` request against the URI of the note's
`note-tags` link:

include::{generated}/get-tags/request.asciidoc[]

The response shows that, as expected, the note has a single tag:

include::{generated}/get-tags/response.asciidoc[]



[getting-started-tagging-a-note-existing]
=== Tagging an existing note
An existing note can be tagged by executing a `PATCH` request against the note's URI with
a body that contains the array of tags to be associated with the note. We'll used the
URI of the untagged note that we created earlier:

include::{generated}/tag-existing-note/request.asciidoc[]

This request should produce a `204 No Content` response:

include::{generated}/tag-existing-note/response.asciidoc[]

When we first created this note, we noted the `note-tags` link included in its details:

include::{generated}/get-note/response.asciidoc[]

We can use that link now and execute a `GET` request to see that the note now has a
single tag:

include::{generated}/get-tags-for-existing-note/request-response.asciidoc[]
